export const SearchTypes = Object.freeze({
  q: 'query',
  title: 'title',
  author: 'author',
  subject: 'subject',
});

export const SortTypes = Object.freeze({
  ['new']: 'New',
  ['old']: 'Old',
  ['rating desc']: 'Rated',
  ['want_to_read']: 'Famous',
  ['title']: 'Title',
});

export const Subjects = Object.freeze({
  Architecture: 'Architecture',
  'Art Instruction': 'Art Instruction',
  'Art History': 'Art History',
  Dance: 'Dance',
  Design: 'Design',
  Fashion: 'Fashion',
  Film: 'Film',
  'Graphic Design': 'Graphic Design',
  Music: 'Music',
  'Music Theory': 'Music Theory',
  Painting: 'Painting',
  Photography: 'Photography',
  Bears: 'Bears',
  Cats: 'Cats',
  Kittens: 'Kittens',
  Dogs: 'Dogs',
  Puppies: 'Puppies',
  Fantasy: 'Fantasy',
  'Historical Fiction': 'Historical Fiction',
  Horror: 'Horror',
  Humor: 'Humor',
  Literature: 'Literature',
  Magic: 'Magic',
  'Mystery and detective stories': 'Mystery and detective stories',
  Plays: 'Plays',
  Poetry: 'Poetry',
  Romance: 'Romance',
  'Science Fiction': 'Science Fiction',
  'Short Stories': 'Short Stories',
  Thriller: 'Thriller',
  'Young Adult': 'Young Adult',
  Biology: 'Biology',
  Chemistry: 'Chemistry',
  Mathematics: 'Mathematics',
  Physics: 'Physics',
  Programming: 'Programming',
  Management: 'Management',
  Entrepreneurship: 'Entrepreneurship',
  'Business Economics': 'Business Economics',
  'Business Success': 'Business Success',
  Finance: 'Finance',
  'Kids Books': 'Kids Books',
  'Stories in Rhyme': 'Stories in Rhyme',
  'Baby Books': 'Baby Books',
  'Bedtime Books': 'Bedtime Books',
  'Picture Books': 'Picture Books',
  'Ancient Civilization': 'Ancient Civilization',
  Archaeology: 'Archaeology',
  Anthropology: 'Anthropology',
  'World War II': 'World War II',
  'Social Life and Customs': 'Social Life and Customs',
  Cooking: 'Cooking',
  Cookbooks: 'Cookbooks',
  'Mental Health': 'Mental Health',
  Exercise: 'Exercise',
  Nutrition: 'Nutrition',
  'Self-help': 'Self-help',
  Autobiographies: 'Autobiographies',
  History: 'History',
  'Politics and Government': 'Politics and Government',
  Women: 'Women',
  'Kings and Rulers': 'Kings and Rulers',
  Composers: 'Composers',
  Artists: 'Artists',
  Religion: 'Religion',
  'Political Science': 'Political Science',
  Psychology: 'Psychology',
  Education: 'Education',
  'Business & Economics': 'Business & Economics',
  Science: 'Science',
  'English Language': 'English Language',
  'Computer Science': 'Computer Science',
});
