import type {Metadata} from 'next';
import './globals.css';
import {FontFamilies} from '@/constants/types';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${FontFamilies.wotfard} antialiased py-6 px-12 font-wotfard font-wotfardRg scrollbar`}>
        {children}
      </body>
    </html>
  );
}
